// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Attachments
{
    [Key]
    [Column("AttachmentID")]
    public int AttachmentId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ContentType { get; set; }

    public int? Size { get; set; }

    public int CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDate { get; set; }

    public int? Version { get; set; }

    public int? Status { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Tags { get; set; }

    [InverseProperty("Attachment")]
    public virtual ICollection<BlogAttachments> BlogAttachments { get; set; } = new List<BlogAttachments>();

    [ForeignKey("CreatedBy")]
    [InverseProperty("AttachmentsCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("Attachment")]
    public virtual ICollection<ProductAttachments> ProductAttachments { get; set; } = new List<ProductAttachments>();

    [InverseProperty("Attachment")]
    public virtual ICollection<ReviewAttachments> ReviewAttachments { get; set; } = new List<ReviewAttachments>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("AttachmentsUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}