// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

[PrimaryKey("BlogId", "AttachmentId")]
[Index("BlogId", Name = "idx_BlogAttachments_BlogID")]
public partial class BlogAttachments
{
    [Key]
    [Column("BlogID")]
    public int BlogId { get; set; }

    [Key]
    [Column("AttachmentID")]
    public int AttachmentId { get; set; }

    [ForeignKey("AttachmentId")]
    [InverseProperty("BlogAttachments")]
    public virtual Attachments Attachment { get; set; }

    [ForeignKey("BlogId")]
    [InverseProperty("BlogAttachments")]
    public virtual Blogs Blog { get; set; }
}