// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Blogs
{
    [Key]
    [Column("BlogID")]
    public int BlogId { get; set; }

    [StringLength(255)]
    public string Title { get; set; }

    [Column(TypeName = "text")]
    public string Content { get; set; }

    [Column("ReviewID")]
    public int ReviewId { get; set; }

    [Column("ImageURL")]
    [StringLength(255)]
    public string ImageUrl { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [InverseProperty("Blog")]
    public virtual ICollection<BlogAttachments> BlogAttachments { get; set; } = new List<BlogAttachments>();

    [ForeignKey("CreatedBy")]
    [InverseProperty("BlogsCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [ForeignKey("ReviewId")]
    [InverseProperty("Blogs")]
    public virtual Reviews Review { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("BlogsUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}