// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Brand
{
    [Key]
    [Column("BrandID")]
    public int BrandId { get; set; }

    [Required]
    [StringLength(50)]
    public string BrandName { get; set; }

    [Column("ImageURL")]
    [StringLength(255)]
    public string ImageUrl { get; set; }

    public int? CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("BrandCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("Brand")]
    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("BrandUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}