// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Categories
{
    [Key]
    [Column("CategoryID")]
    public int CategoryId { get; set; }

    [StringLength(50)]
    public string CategoryName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("CategoriesCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<Subcategories> Subcategories { get; set; } = new List<Subcategories>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("CategoriesUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}