// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Cities
{
    [Key]
    [Column("CityID")]
    public int CityId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string CityName { get; set; }

    [Column("StateID")]
    public int? StateId { get; set; }

    [ForeignKey("StateId")]
    [InverseProperty("Cities")]
    public virtual States State { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<UserAddresses> UserAddresses { get; set; } = new List<UserAddresses>();
}