// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Coupons
{
    [Key]
    [Column("CouponID")]
    public int CouponId { get; set; }

    [StringLength(20)]
    public string CouponCode { get; set; }

    public int? DiscountPercent { get; set; }

    public int? MaxUses { get; set; }

    public int? Uses { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    public bool AppliesToProducts { get; set; }

    public bool AppliesToCategories { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("CouponsCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("Coupon")]
    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("CouponsUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}