// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Inventory
{
    [Key]
    [Column("ProductID")]
    public int ProductId { get; set; }

    public int? Quantity { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("InventoryCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Inventory")]
    public virtual Products Product { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("InventoryUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}