// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class LanguageTranslations
{
    [Key]
    [Column("LanguageTranslationID")]
    public int LanguageTranslationId { get; set; }

    [Column("LanguageID")]
    public int LanguageId { get; set; }

    [Required]
    [StringLength(100)]
    public string TranslationKey { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string TranslationValue { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("LanguageTranslationsCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [ForeignKey("LanguageId")]
    [InverseProperty("LanguageTranslations")]
    public virtual Languages Language { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("LanguageTranslationsUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}