// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Languages
{
    [Key]
    [Column("LanguageID")]
    public int LanguageId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [StringLength(10)]
    public string Code { get; set; }

    [InverseProperty("Language")]
    public virtual ICollection<LanguageTranslations> LanguageTranslations { get; set; } = new List<LanguageTranslations>();
}