// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Logs
{
    [Key]
    [Column("LogID")]
    public int LogId { get; set; }

    [Required]
    [StringLength(320)]
    [Unicode(false)]
    public string Related { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    [Required]
    public string Detail { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }
}