// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

[Index("OrderStatusId", Name = "idx_Orders_OrderStatusID")]
[Index("UserId", Name = "idx_Orders_UserID")]
public partial class Orders
{
    [Key]
    [Column("OrderID")]
    public int OrderId { get; set; }

    [Column("CouponID")]
    public int? CouponId { get; set; }

    [Column("AddressID")]
    public int AddressId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column("PaymentMethodID")]
    public int PaymentMethodId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalCost { get; set; }

    [Column("OrderStatusID")]
    public int OrderStatusId { get; set; }

    public int? TrackingNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ShippedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeliveredDate { get; set; }

    [ForeignKey("AddressId")]
    [InverseProperty("Orders")]
    public virtual UserAddresses Address { get; set; }

    [ForeignKey("CouponId")]
    [InverseProperty("Orders")]
    public virtual Coupons Coupon { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItems> OrderItems { get; set; } = new List<OrderItems>();

    [ForeignKey("OrderStatusId")]
    [InverseProperty("Orders")]
    public virtual OrderStatuses OrderStatus { get; set; }

    [ForeignKey("PaymentMethodId")]
    [InverseProperty("Orders")]
    public virtual PaymentMethods PaymentMethod { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<Refunds> Refunds { get; set; } = new List<Refunds>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual Users User { get; set; }
}