// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class PaymentMethods
{
    [Key]
    [Column("PaymentMethodID")]
    public int PaymentMethodId { get; set; }

    [StringLength(255)]
    public string Thumbnail { get; set; }

    [StringLength(50)]
    public string PaymentMethodName { get; set; }

    [StringLength(255)]
    public string PaymentMethodDetails { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("PaymentMethodsCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("PaymentMethod")]
    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("PaymentMethodsUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}