// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

[PrimaryKey("ProductId", "AttachmentId")]
[Index("ProductId", Name = "idx_ProductAttachments_ProductID")]
public partial class ProductAttachments
{
    [Key]
    [Column("ProductID")]
    public int ProductId { get; set; }

    [Key]
    [Column("AttachmentID")]
    public int AttachmentId { get; set; }

    [ForeignKey("AttachmentId")]
    [InverseProperty("ProductAttachments")]
    public virtual Attachments Attachment { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductAttachments")]
    public virtual Products Product { get; set; }
}