// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Products
{
    [Key]
    [Column("ProductID")]
    public int ProductId { get; set; }

    [StringLength(50)]
    public string ProductName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Column("SubcategoryID")]
    public int SubcategoryId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [Column("BrandID")]
    public int BrandId { get; set; }

    [Column("ScentNoteID")]
    public int ScentNoteId { get; set; }

    [Column("SizeID")]
    public int SizeId { get; set; }

    [Column("ImageURL")]
    [StringLength(255)]
    public string ImageUrl { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("BrandId")]
    [InverseProperty("Products")]
    public virtual Brand Brand { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<CartItems> CartItems { get; set; } = new List<CartItems>();

    [ForeignKey("CreatedBy")]
    [InverseProperty("ProductsCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("Product")]
    public virtual Inventory Inventory { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderItems> OrderItems { get; set; } = new List<OrderItems>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductAttachments> ProductAttachments { get; set; } = new List<ProductAttachments>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductIngredient> ProductIngredient { get; set; } = new List<ProductIngredient>();

    [InverseProperty("Product")]
    public virtual ICollection<Reviews> Reviews { get; set; } = new List<Reviews>();

    [ForeignKey("ScentNoteId")]
    [InverseProperty("Products")]
    public virtual ScentNote ScentNote { get; set; }

    [ForeignKey("SizeId")]
    [InverseProperty("Products")]
    public virtual Size Size { get; set; }

    [ForeignKey("SubcategoryId")]
    [InverseProperty("Products")]
    public virtual Subcategories Subcategory { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("ProductsUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}