// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Refunds
{
    [Key]
    [Column("RefundID")]
    public int RefundId { get; set; }

    [Column("OrderID")]
    public int OrderId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? RefundAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RefundDate { get; set; }

    [Column("RefundStatusID")]
    public int RefundStatusId { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("RefundsCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Refunds")]
    public virtual Orders Order { get; set; }

    [ForeignKey("RefundStatusId")]
    [InverseProperty("Refunds")]
    public virtual RefundStatuses RefundStatus { get; set; }

    [ForeignKey("UpdatedBy")]
    [InverseProperty("RefundsUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}