// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class RefundStatuses
{
    [Key]
    [Column("RefundStatusID")]
    public int RefundStatusId { get; set; }

    [StringLength(50)]
    public string RefundStatusName { get; set; }

    [StringLength(255)]
    public string RefundStatusDescription { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("RefundStatusesCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("RefundStatus")]
    public virtual ICollection<Refunds> Refunds { get; set; } = new List<Refunds>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("RefundStatusesUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}