// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

[PrimaryKey("ReviewId", "AttachmentId")]
[Index("ReviewId", Name = "idx_ReviewAttachments_ReviewID")]
public partial class ReviewAttachments
{
    [Key]
    [Column("ReviewID")]
    public int ReviewId { get; set; }

    [Key]
    [Column("AttachmentID")]
    public int AttachmentId { get; set; }

    [ForeignKey("AttachmentId")]
    [InverseProperty("ReviewAttachments")]
    public virtual Attachments Attachment { get; set; }

    [ForeignKey("ReviewId")]
    [InverseProperty("ReviewAttachments")]
    public virtual Reviews Review { get; set; }
}