// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Reviews
{
    [Key]
    [Column("ReviewID")]
    public int ReviewId { get; set; }

    [Column("ProductID")]
    public int ProductId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    public byte? Rating { get; set; }

    [Column(TypeName = "text")]
    public string Comment { get; set; }

    public bool IsApproved { get; set; }

    [InverseProperty("Review")]
    public virtual ICollection<Blogs> Blogs { get; set; } = new List<Blogs>();

    [ForeignKey("ProductId")]
    [InverseProperty("Reviews")]
    public virtual Products Product { get; set; }

    [InverseProperty("Review")]
    public virtual ICollection<ReviewAttachments> ReviewAttachments { get; set; } = new List<ReviewAttachments>();

    [ForeignKey("UserId")]
    [InverseProperty("Reviews")]
    public virtual Users User { get; set; }
}