// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class ScentNote
{
    [Key]
    [Column("ScentNoteID")]
    public int ScentNoteId { get; set; }

    [Required]
    [StringLength(50)]
    public string ScentNoteName { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("ScentNoteCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("ScentNote")]
    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("ScentNoteUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}