// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

[Table("SMS")]
public partial class Sms
{
    [Key]
    public int MessageId { get; set; }

    [Column(TypeName = "decimal(18, 3)")]
    public decimal Cost { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Message { get; set; }

    public byte Status { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Sender { get; set; }

    [Precision(0)]
    public DateTime? CreatedDate { get; set; }
}