// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

[Index("StateName", Name = "UQ_States_State", IsUnique = true)]
public partial class States
{
    [Key]
    [Column("StateID")]
    public int StateId { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string StateName { get; set; }

    [InverseProperty("State")]
    public virtual ICollection<Cities> Cities { get; set; } = new List<Cities>();
}