// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class Subcategories
{
    [Key]
    [Column("SubcategoryID")]
    public int SubcategoryId { get; set; }

    [StringLength(50)]
    public string SubcategoryName { get; set; }

    [Column("CategoryID")]
    public int CategoryId { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Subcategories")]
    public virtual Categories Category { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("SubcategoriesCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("Subcategory")]
    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("SubcategoriesUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}