// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class SupportCategories
{
    [Key]
    [Column("CategoryID")]
    public int CategoryId { get; set; }

    [StringLength(255)]
    public string CategoryName { get; set; }

    public int CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("SupportCategoriesCreatedByNavigation")]
    public virtual Users CreatedByNavigation { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<SupportTickets> SupportTickets { get; set; } = new List<SupportTickets>();

    [ForeignKey("UpdatedBy")]
    [InverseProperty("SupportCategoriesUpdatedByNavigation")]
    public virtual Users UpdatedByNavigation { get; set; }
}