// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

[Index("TicketId", Name = "idx_SupportMessages_TicketID")]
public partial class SupportMessages
{
    [Key]
    [Column("MessageID")]
    public int MessageId { get; set; }

    [Column("TicketID")]
    public int TicketId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(1200)]
    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Timestamp { get; set; }

    [ForeignKey("TicketId")]
    [InverseProperty("SupportMessages")]
    public virtual SupportTickets Ticket { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("SupportMessages")]
    public virtual Users User { get; set; }
}