// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

[Index("UserId", Name = "idx_UserAddresses_UserID")]
public partial class UserAddresses
{
    [Key]
    [Column("AddressID")]
    public int AddressId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(255)]
    public string AddressLine1 { get; set; }

    [StringLength(255)]
    public string AddressLine2 { get; set; }

    [Column("CityID")]
    public int CityId { get; set; }

    [StringLength(50)]
    public string State { get; set; }

    [StringLength(50)]
    public string Country { get; set; }

    [StringLength(20)]
    public string PostalCode { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("UserAddresses")]
    public virtual Cities City { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    [ForeignKey("UserId")]
    [InverseProperty("UserAddresses")]
    public virtual Users User { get; set; }
}