// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Yani.Models.Database;

public partial class WebsiteVisitors
{
    [Key]
    [Column("VisitorID")]
    public int VisitorId { get; set; }

    [Required]
    [Column("IPAddress")]
    [StringLength(50)]
    public string Ipaddress { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime VisitDate { get; set; }

    [Required]
    [StringLength(255)]
    public string PageVisited { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("WebsiteVisitors")]
    public virtual Users User { get; set; }
}